### ISSUE TITLE
Game doesn't works

### ISSUE THREAD

**Issue by i-priyanshuverma** [angle943/tic-tac-toe#1]
This backend code doesn't works. Can't play the game, neither X nor O can be used.

**Comment by Ripfumelo-Nova-Magomani** [comment]
pleas recheck your work each line and if i may ask which text editor are using to run your  code

**Comment by i-priyanshuverma** [comment]
I'm using VS code editor, and I've tried few times but after getting
frustrated. I decided to direct copy and paste the whole code instead of
writing, but then also the same thing happened. Hi was working, but
couldn't play the game neither with X nor with O.

**Comment by Ripfumelo-Nova-Magomani** [comment]
Why in my side is working I can play the game ... Like I play the game
everyday even this morning I was playing ...maybe the something wrong
somewhere with your machine ...have u tried restarting your machine ...

**Comment by i-priyanshuverma** [comment]
I'll try it on my another pc and will let you know.

**Comment by Ripfumelo-Nova-Magomani** [comment]
Yes maybe try that and hit me up the output
